#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2017 Zhang Hao
#
class Const:
    COOKIE_USER_KEY = "user"
    TASK_STATUS_PREPARE = 'TASK_STATUS_000'
    TASK_STATUS_INPROCESS = 'TASK_STATUS_001'
    TASK_STATUS_FINISHED = 'TASK_STATUS_002'
    TASK_STATUS_UNFINISHED = 'TASK_STATUS_003'
    TASK_STATUS_DELAYED = 'TASK_STATUS_004'
    TASK_STATUS_URGENT = 'TASK_STATUS_005'

    TASK_APPROVE_STATUS_NONE = ''
    TASK_APPROVE_STATUS_PERSONAL = '0'
    TASK_APPROVE_STATUS_SCHEDULED = '1'

    DUTY_TIME_TYPE_ALL = 'DUTY_TIME_TYPE_ALL'
    DUTY_TIME_TYPE_ROUTINE = 'DUTY_TIME_TYPE_ROUTINE'
    DUTY_TIME_TYPE_PERIODICAL = 'DUTY_TIME_TYPE_PERIODICAL'
    DUTY_TIME_TYPE_SPECIFIC = 'DUTY_TIME_TYPE_SPECIFIC'
    DUTY_TIME_TYPE_GROUP = 'DUTY_TIME_TYPE_GROUP'
    DUTY_PERIOD_TYPE_WEEK = 'DUTY_PERIOD_TYPE_WEEK'
    DUTY_PERIOD_TYPE_MONTH = 'DUTY_PERIOD_TYPE_MONTH'

    NOTIFY_TIME_TYPE_BEFORE = 'before'
    NOTIFY_TIME_TYPE_AFTER = 'after'
    NOTIFY_TIME_TYPE_SPECIFIC = 'specific'

    NOTIFY_TYPE_MESSAGE_QUEUE = 'message_queue'
    NOTIFY_TYPE_SYSTEM_ALARM = 'system_alarm'
    NOTIFY_TYPE_SHORT_MESSAGE = 'short_message'

    NOTIFY_PRIORITY_HIGH = 'high'
    NOTIFY_PRIORITY_MIDDLE = 'middle'
    NOTIFY_PRIORITY_LOW = 'low'