#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2017 Zhang Hao
#
class Const:
    TASK_STATUS_PREPARE = 'TASK_STATUS_000'
    TASK_STATUS_INPROCESS = 'TASK_STATUS_001'
    TASK_STATUS_FINISHED = 'TASK_STATUS_002'
    TASK_STATUS_UNFINISHED = 'TASK_STATUS_003'
    TASK_STATUS_DELAYED = 'TASK_STATUS_004'
    TASK_STATUS_URGENT = 'TASK_STATUS_005'

    TASK_APPROVE_STATUS_NONE = ''
    TASK_APPROVE_STATUS_PERSONAL = '0'
    TASK_APPROVE_STATUS_SCHEDULED = '1'