/**
 * Created by HOZ on 28/08/2017.
 */

// define task finsh status
export const TASK_STATUS_PREPARE = 'TASK_STATUS_000'
export const TASK_STATUS_INPROCESS = 'TASK_STATUS_001'
export const TASK_STATUS_FINISHED = 'TASK_STATUS_002'
export const TASK_STATUS_UNFINISHED = 'TASK_STATUS_003'
export const TASK_STATUS_DELAYED = 'TASK_STATUS_004'
export const TASK_STATUS_URGENT = 'TASK_STATUS_005'
export const TASK_STATUS = new Map([
  [TASK_STATUS_PREPARE, '待执行'],
  [TASK_STATUS_INPROCESS, '执行中'],
  [TASK_STATUS_FINISHED, '已完成'],
  [TASK_STATUS_UNFINISHED, '未完成'],
  [TASK_STATUS_DELAYED, '延迟完成'],
  [TASK_STATUS_URGENT, '已完成']
])

export const TASK_TYPE_NORMAL = '0'
export const TASK_TYPE_ROUTINE = '1'

export const TASK_TYPES = new Map([
  [TASK_TYPE_ROUTINE, '日常任务'],
  [TASK_TYPE_NORMAL, '一般任务']
])

export const PERMISSIONS = {
  'PERMISSION_USER_ADD': 'C_001_P_001',
  'PERMISSION_USER_REMOVE': 'C_001_P_002',
  'PERMISSION_USER_EDIT': 'C_001_P_003',
  'PERMISSION_ROLE_ADD': 'C_002_P_001',
  'PERMISSION_ROLE_REMOVE': 'C_002_P_002',
  'PERMISSION_ROLE_EDIT': 'C_002_P_003',
  'PERMISSION_TASK_QUERY_ALL': 'C_003_P_001',
  'PERMISSION_TASK_EDIT_USER_TASK': 'C_003_P_002',
  'PERMISSION_TASK_QUERY_USER_LOCATION': 'C_003_P_003',
  'PERMISSION_TASK_APPROVE_TASK': 'C_003_P_004',
  'PERMISSION_TASK_ADD_TEMP_TASK': 'C_003_P_005'
}
export const PERMISSION_CATEGORIES = {
  'PERMISSION_CATEGORY_USER': 'C_001',
  'PERMISSION_CATEGORY_ROLE': 'C_002',
  'PERMISSION_CATEGORY_TASK': 'C_003',
  'PERMISSION_CATEGORY_PERMISSIONROLE': 'C_004'
}
